name: Build Windows App

on:
  workflow_dispatch: {}

jobs:
  build_windows:
    name: Build Windows App
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Cache Pub dependencies
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\Pub\Cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Get dependencies
        run: flutter pub get
        
      - name: Build Windows
        run: flutter build windows --release --obfuscate --split-debug-info=build/windows/symbols

      - name: Compile Inno Setup Installer
        run: iscc windows\installer.iss
        
      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: DuoShare-Setup-Windows
          path: build\windows\x64\installer\DuoShare-Setup.exe
