name: Build Android APK

on:
  workflow_dispatch: {}

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get
        
      - name: Build APK (split per ABI)
        run: flutter build apk --release --split-per-abi
        
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: DuoShare-Release-APKs
          path: build/app/outputs/flutter-apk/app-*-release.apk
